// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA6ewMExof0YOmuYR9QxCcym15l9RRc4I',
    appId: '1:262412583442:web:51e3c99c17c0eaad720ecb',
    messagingSenderId: '262412583442',
    projectId: 'flutter-login-app-bfb8b',
    authDomain: 'flutter-login-app-bfb8b.firebaseapp.com',
    storageBucket: 'flutter-login-app-bfb8b.appspot.com',
    measurementId: 'G-JBHH8N87ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1H02-GLDPMOWpkEhMm-ft5cnpP2Ol6w',
    appId: '1:262412583442:android:4bd6a133e25300f2720ecb',
    messagingSenderId: '262412583442',
    projectId: 'flutter-login-app-bfb8b',
    storageBucket: 'flutter-login-app-bfb8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldQpuhFLWBcaPEl9lCLFB_hitOQJmHNc',
    appId: '1:262412583442:ios:c1e9680f6b9fe5ea720ecb',
    messagingSenderId: '262412583442',
    projectId: 'flutter-login-app-bfb8b',
    storageBucket: 'flutter-login-app-bfb8b.appspot.com',
    iosBundleId: 'com.example.basicLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldQpuhFLWBcaPEl9lCLFB_hitOQJmHNc',
    appId: '1:262412583442:ios:8cad177bdefea473720ecb',
    messagingSenderId: '262412583442',
    projectId: 'flutter-login-app-bfb8b',
    storageBucket: 'flutter-login-app-bfb8b.appspot.com',
    iosBundleId: 'com.example.basicLoginApp.RunnerTests',
  );
}
